### ISSUE TITLE
yarn build issue

### ISSUE THREAD

**Issue by yml-blog** [FacilMap/facilmap2#318]
[facilmap-types]: Process started
[facilmap-types]: vite v5.2.8 building for production...
[facilmap-types]: ✓ 0 modules transformed.
[facilmap-types]: x Build failed in 1.84s
[facilmap-types]: error during build:
[facilmap-types]: RollupError: Entry module "src/index.ts" cannot be external.
[facilmap-types]:     at getRollupError (file:///C:/Users/liym1/facilmap/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
[facilmap-types]:     at error (file:///C:/Users/liym1/facilmap/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
[facilmap-types]:     at ModuleLoader.loadEntryModule (file:///C:/Users/liym1/facilmap/node_modules/rollup/dist/es/shared/node-entry.js:18952:20)
[facilmap-types]:     at async Promise.all (index 0)
[facilmap-types]: Process exited (exit code 1), completed in 2s 669ms

**Comment by cdauth** [comment]
Interesting. I cannot reproduce this on my machine. I suspect it might be an issue that occurs only on Windows.
Could you, in `types/vite.config.ts`, replace the line that starts with `external:` with this:
```typescript
			external: (id) => { console.log(id); return !id.startsWith("./") && !id.startsWith("../") && !id.startsWith("/") }
```

and then run the command again and post the output here?

**Comment by cdauth** [comment]
Thanks. I have pushed a potential fix for this. Could you try again?
